<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            table {
                padding-top: 10px;
                margin: 0 auto;
                border-collapse: collapse;
                width: 90%;
            }


            th, td {
                text-align: left;
                padding: 8px;
            }

            tr:nth-child(even){background-color: #f2f2f2}

            th {
                background-color: #4CAF50;
                color: white;
            }
        </style>
    </head>
    <body>
        <h1>Employees</h1>
        <div>GridView</div>

        <div>
            <table>
                <tr>
                    <th>Name</th>
                    <th>Email<br><div><form action="grid" method="post">
                                <input type="search" value="<?= $search; ?>" name="search">
                            </form></div></th>
                    <th>Position</th>
                    <th>Salary</th>
                    <th>Action</th>
                </tr>

                <?php if(isset($employees)): ?>
                <?php foreach ($employees as $employee): ?>
                <tr>
                    <td><?= $employee->name ?></td>
                    <td><?= $employee->email ?></td>
                    <td><?= $employee->position ?></td>
                    <td><?= $employee->salary ?></td>
                    <td><a href="view/<?= $employee->id ?>">Edit</a></td>
                </tr>
                <?php endforeach; ?>
                <?php else: ?>
                    <tr><td colspan="5">There is no data to display.</td></tr>
                <?php endif; ?>

            </table>
        </div>
    </body>
</html>
